routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

\Illuminate\Support\Facades\Auth::routes(["register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware("auth")->group(function () {
    Route::resource("/users", "UserController");
    
    Route::get("/photoTypes", "PhotoTypeController@index")->name('photoTypes.index');
    Route::get("/photoTypes/search/{type}", "PhotoTypeController@index");
    Route::get("/photoTypes/create", "PhotoTypeController@create")->name('photoTypes.create');
    Route::post("/photoTypes", "PhotoTypeController@store")->name('photoTypes.store');
    Route::resource("/photoTypes", "PhotoTypeController")->except(["index"]);

    Route::resource("/photos", "PhotoController");
    Route::post("/photos/uploadFile", "PhotoController@uploadFile");
    Route::post("/photos/deleteFile", "PhotoController@deleteFile");
    Route::post("/photos/deletePicture/{route}", "PhotoController@deletePicture");

    Route::resource("/logos", "LogoController");
    Route::post("/logos/uploadFile", "LogoController@uploadFile");
    Route::post("/logos/deleteFile", "LogoController@deleteFile");
       
    Route::post("/novedades/uploadFile", "NovedadController@uploadFile");
    Route::post("/novedades/deleteFile", "NovedadController@deleteFile");
    Route::resource("/novedades", "NovedadController")->parameters(['novedades' => 'novedad']);

    Route::resource("/vacantes","VacanteController");
        
    Route::resource("/settings", "SettingController")->except("show");
});

resources/views/album/all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Editor de fotos
                        <a class="btn btn-success btn-sm float-right" href="{{route('photos.create',["type"=>$_GET["type"]])}}"
                           data-toggle="tooltip" data-placement="right" title="Agregar foto nueva">
                            <i class="fa fa-plus"></i> Nueva
                        </a>
                        
                    </div>
                    <div class="card-body">
                        <x-table :columns="$columns" :dataTablesColumns="$dataTablesColumns" :route="$route"
                                 :config="$config" name="photos"/>
                        <x-modal :title="__('blogs.save.title')" :cancel="true" :save="true" size="modal-lg">
                            <form id="form">
                            <input type="hidden" id="edit">
                            <div class="form-group row">
                                <label for="title" class="col-sm-3 col-form-label">Hola</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="title"
                                           placeholder="{{__("photos.labels.title")}}">
                                    <span class="error" id="error_title"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="title" class="col-sm-3 col-form-label">{{__("photos.labels.category")}}</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="category" id="category">
                                        <option selected>-- Seleccione --</option>
                                    </select>
                                    <span class="error" id="error_category"></span>
                                </div>
                            </div>
                            </form>
                        </x-modal>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        var table;
        
        let functions = new Functions();
        $(function () {
            $("#alert").hide();
            $('[data-toggle="tooltip"]').tooltip()
        })

        /** start request delete title blogs **/
        function drop(blogId) {
            let response;
            let alert = new Alerts();
            alert.warning(
                "{{__("general.alert-type.warning")}}",
                "{{__("general.delete.message")}}",
                {yes: "{{__("general.buttons.yes")}}", no: "{{__("general.buttons.no")}}"},
                async function () {
                
                response = await functions.request('{{url("photos")}}/' + blogId, "DELETE");
                
                if (response) {
                    swal("{{__("general.delete.title")}}", response, "success");
                    table.ajax.reload();
                }
            });
        }

        /** end request delete blog **/
        /** start request show blog **/
        function show() {
            clearErrors();
            $("#titleModal").html("{{__("novedades.save.title")}}")
            $("#edit").val("");
            $("#form").trigger("reset");
            $("#modal").modal({keyboard: false})
            
        }
        /** end request show blog **/

        /** start request create title blogs **/
        function create() {
            clearErrors();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{route("photos.store")}}', "POST", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#text-load").hide();
                $("#primary").removeAttr("disabled");
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Created!", "{{__("novedades.save.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request create blog **/

        /** start request get title blogs **/
        async function get(blogId) {
            let response;
            console.log(blogId);
            clearErrors();
            response = await functions.request('{{url("/photos")}}/'+blogId, "GET");
            
            if (response) {
                $("#titleModal").html("{{__("photos.edit.title")}}")
                $("#edit").val(blogId);
                $("#title").val(response.data.title);
                $("#category").val(response.data.category_id).change();
                $("#modal").modal("show");
            }
        }
        /** end request get blog **/

        /** start request edit title blogs **/
        function edit() {
            clearErrors();
            let blogId = $("#edit").val();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{url("/photos")}}/'+blogId, "PATCH", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Updated!", "{{__("novedades.edit.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request edit blog **/
        function execute() {
            if ($("#edit").val() === "") {
                return create();
            }
            return edit();
        }

        function clearErrors() {
            $("#error_title").html("").hide();
            $("#error_category").html("").hide();
        }
    </script>
@endsection

resources/views/album/button_action.blade.php
<div>
    {{--<a type="button" class="btn btn-info btn-sm" href="{{route("album.show", $model->getAttribute("id"))}}"
            data-toggle="tooltip" data-placement="right" title="{{__("photos.all.tooltip-show")}}">
        <i class="fa fa-eye"></i>
    </a>--}}
    <a class="btn btn-warning btn-sm" href="{{route("photos.edit", $model->getAttribute("id"))}}"
       data-toggle="tooltip" data-placement="right" title="{{__("photos.all.tooltip-edit")}}">
        <i class="fa fa-pencil"></i>
    </a>
    <button type="button" class="btn btn-danger btn-sm" onclick="drop({{$model->getAttribute("id")}})"
            data-toggle="tooltip" data-placement="right" title="{{__("photos.all.tooltip-destroy")}}">
        <i class="fa fa-trash"></i>
    </button>
</div>

resources/views/album/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Editor de fotos - Seleccione la categoría.</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <p>Estas son las categorías disponibles:</p>
                    <div class="container d-flex justify-content flex-wrap">
                    
                    
                    @foreach ($types as $type)
                        @if (in_array($type->id , $editables))
                        <div class="m-2">
                            <a href="{{route("photos.index",["type"=>$type->id])}}"", class="btn btn-primary">{{ucfirst($type->id_name)}}</a>
                        </div>
                        @else
                        <div class="m-2">
                            <a href="/photoTypes/search/{{$type->id}}" class="btn btn-primary">{{ucfirst($type->id_name)}}</a>
                        </div>
                        @endif
                    @endforeach
                    @if (in_array($types[0]->id , $editables))
                        <div class="m-2">
                            <a href="{{route("photoTypes.create",["type"=>$types[0]->parent_photo_type])}}"", class="btn btn-secondary">Agregar nueva categoría</a>
                        </div>
                    @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/album/newType.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form
            action="{{isset($data) ? route("photos.update", $data["id"]) : route("photoTypes.store")}}"
            method="POST"
            id="form"
            enctype="multipart/form-data"
        >
        <input type="hidden" name="path" value="{{$path}}">
        <input type="hidden" name="phototype_id" value="@if(!empty($_GET["type"])) {{$_GET["type"]}}@endif">               
           
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <span id="message"></span>
                    <div class="card">
                        <div class="card-header">Agregar nueva categoría</div>
                        <div class="card-body">
                            @if ($errors->any() || session()->has("message"))
                                @php
                                    $type = session()->has("message") ? "success" : "danger";
                                    $message = session()->has("message") ? session()->get("message") : __('validation.message');
                                @endphp
                                <x-alert :message="$message" :type="$type" :show="true" duration="100000"/>
                            @endif
                            <div class="form-group">
                                <label for="name">Nombre en Español</label>
                                <input type="text"
                                       class="form-control"
                                       id="name"
                                       name="name"
                                       required
                                       placeholder="Nombre"
                                       value="{{ isset($data) ? $data["name"] : old("name") }}"
                                />
                            </div>
                            <div class="form-group">
                                <label for="name_en">Nombre en Inglés</label>
                                <input type="text"
                                       class="form-control"
                                       id="name_en"
                                       name="name_en"
                                       required
                                       placeholder="Nombre en inglés"
                                       value="{{ isset($data) ? $data["name_en"] : old("name_en") }}"
                                />
                            </div>
                            <div class="form-group">
                                <label for="name">Nombre en Francés</label>
                                <input type="text"
                                       class="form-control"
                                       id="name_fr"
                                       name="name_fr"
                                       required
                                       placeholder="Nombre en francés"
                                       value="{{ isset($data) ? $data["name_fr"] : old("name_fr") }}"
                                />
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary float-right"
                                    id="save">{{isset($data) ? __("general.buttons.edit") :__("general.buttons.save")}}</button>
                            </div>
                                          
                        </div>
                    </div>
                </div>
                
            </div>
        </form>
    </div>
@endsection
@section("js")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
@endsection
@section('css')
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
@endsection
@section("scripts")
    <script type="application/javascript">
        $(document).ready(function() {
            if (!$("#publish").is(':checked')) {
                $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
            }
            $("#publish").change( function(){
                if( $(this).is(':checked') ) {
                    $("#datetime").removeAttr("readOnly").datepicker("option", "disabled", false);
                }else{
                    $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
                }
            });
            var now = moment();
            let date = $("#datetime").val().length < 0 ? $("#datetime").val() : now.format('DD/MM/YYYY');
            $('#datetime').datepicker({
                changeMonth: true,
                changeYear: true,
            });

            $.datepicker.regional['es'];
        });
        
    </script>
    <script type="application/javascript">

        
        let functions = new Functions();
        
               

        function removeItemFromArr(arr, item) {
            let i = arr.indexOf( item );

            if ( i !== -1 ) {
                arr.splice( i, 1 );
            }
        }

        
    </script>
@endsection

resources/views/album/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form
            action="{{isset($data) ? route("photos.update", $data["id"]) : route("photos.store")}}"
            method="POST"
            id="form"
            enctype="multipart/form-data"
        >
        <input type="hidden" name="path" value="{{$path}}">
        <input type="hidden" name="phototype_id" 
        value="
            @if(!empty($_GET["type"]))
            {{$_GET["type"]}}
            @elseif(isset($data))
            {{$data["phototype_id"]}}
            @else
            {{old("phototype_id")}}
            @endif
        ">               
            @isset($data)
                @method("PUT")
                <input type="hidden" name="file" value="{{$data["file"]}}">
                <input type="hidden" name="id" value="{{$data["id"]}}">
            @endisset
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <span id="message"></span>
                    <div class="card">
                        <div class="card-header">Subir nueva imágen</div>
                        <div class="card-body">
                            @if ($errors->any() || session()->has("message"))
                                @php
                                    $type = session()->has("message") ? "success" : "danger";
                                    $message = session()->has("message") ? session()->get("message") : __('validation.message');
                                @endphp
                                <x-alert :message="$message" :type="$type" :show="true" duration="100000"/>
                            @endif
                            <div class="form-group">
                                <label for="name">Nombre</label>
                                <input type="text"
                                       class="form-control"
                                       id="name"
                                       name="name"
                                       required
                                       placeholder="Nombre"
                                       value="{{ isset($data) ? $data["name"] : old("name") }}"
                                />
                            </div>
                            <div class="form-group">
                                <label for="name">Epígrafe</label>
                                <input type="text"
                                       class="form-control"
                                       id="epigraph"
                                       name="epigraph"
                                       
                                       placeholder="Epígrafe"
                                       value="{{ isset($data) ? $data["epigraph"] : old("epigraph") }}"
                                />
                            </div>
                           
                            <div class="form-group">
                                <label for="name">Orden</label>
                                <input type="text"
                                       class="form-control"
                                       id="order"
                                       name="order"
                                       required
                                       placeholder="{{isset($maximo) ? "El último nro es ".$maximo : "Nro de Orden"}}"
                                       value="{{ isset($data) ? $data["order"] : old("order") }}"
                                />
                            </div>
                                          
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="p-4 card">
                        
                            <div class="form-group">
                                <label for="main_image">Imágen</label>
                                <div>
                                    <div class="file-loading">
                                        <input id="main_image" name="image" type="file">
                                    </div>
                                </div>
                            </div>

                            <div id="kv-avatar-errors-2"></div>
                            
                           
                            <div class="dropdown-divider"></div>
                            <div class="form-group">
                                <button class="btn btn-primary float-right"
                                    id="save">{{isset($data) ? __("general.buttons.edit") :__("general.buttons.save")}}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection
@section("js")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
@endsection
@section('css')
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
@endsection
@section("scripts")
    <script type="application/javascript">
        $(document).ready(function() {
            if (!$("#publish").is(':checked')) {
                $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
            }
            $("#publish").change( function(){
                if( $(this).is(':checked') ) {
                    $("#datetime").removeAttr("readOnly").datepicker("option", "disabled", false);
                }else{
                    $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
                }
            });
            var now = moment();
            let date = $("#datetime").val().length < 0 ? $("#datetime").val() : now.format('DD/MM/YYYY');
            $('#datetime').datepicker({
                changeMonth: true,
                changeYear: true,
            });

            $.datepicker.regional['es'];
        });
        
    </script>
    <script type="application/javascript">

        
        let functions = new Functions();
        $(document).ready(function () {
            $("#main_image").fileinput({
                @if(isset($data) || old("image"))
                    initialPreview: "{{ \Illuminate\Support\Facades\Storage::disk("public")->url($data["file"]) }}",
                    initialPreviewAsData: true,
                    deleteUrl: '{{url("photos/deletePicture", $data["file"])}}',
                    initialPreviewConfig:[
                        {
                            key: "{{ $data["file"] }}",
                        },
                    ],
                    ajaxDeleteSettings: {
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                    },
                @endif
                overwriteInitial: false,
                maxFileSize: 1500,
                showClose: false,
                showCaption: false,
                maxFileCount: 1,
                msgFileRequired: "Archivo requerido",
                browseIcon: " <i class='fa fa-folder-open-o'></i>",
                browseLabel: '',
                removeLabel: '',
                removeIcon: '<i class="fa fa-undo" id="rmain"></i>',
                uploadUrl: '{{url("photos/uploadFile",$path)}}',
                required: true,
                removeTitle: 'Deshacer última acción',
                elErrorContainer: '#kv-avatar-errors-2',
                msgErrorClass: 'alert alert-block alert-danger',
                defaultPreviewContent: '<img src="{{asset("images/file-upload-image-icon.png")}}" class="image" alt="Subir imagen">',
                layoutTemplates: {main2: '{preview} {remove} {browse}'},
                allowedFileExtensions: ["jpg", "png", "gif", "jpeg",],
                ajaxSettings: {
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                previewZoomButtonIcons: {
                    prev: '<i class="fa fa-chevron-left"></i>',
                    next: '<i class="fa fa-chevron-right"></i>',
                    toggleheader: '<i class="fa fa-arrows-h"></i>',
                    fullscreen: '<i class="fa fa-arrows-alt"></i>',
                    borderless: '<i class="fa fa-arrows"></i>',
                    close: '<i class="fa fa-times"></i>'
                },
                fileActionSettings: {
                    showUpload: false,
                    showRemove: false,
                    zoomIcon: "<i class='fa fa-search'></i>",
                    zoomTitle: "Ver imagen",
                    removeIcon: "<i class='fa fa-trash'></i>",
                    removeTitle: "Quitar imagen"
                }
            });
                   
            
        });

        function removeItemFromArr(arr, item) {
            let i = arr.indexOf( item );

            if ( i !== -1 ) {
                arr.splice( i, 1 );
            }
        }

        
    </script>
@endsection