routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

\Illuminate\Support\Facades\Auth::routes(["register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware("auth")->group(function () {
    Route::resource("/users", "UserController");
    
    Route::get("/photoTypes", "PhotoTypeController@index")->name('photoTypes.index');
    Route::get("/photoTypes/search/{type}", "PhotoTypeController@index");
    Route::get("/photoTypes/create", "PhotoTypeController@create")->name('photoTypes.create');
    Route::post("/photoTypes", "PhotoTypeController@store")->name('photoTypes.store');
    Route::resource("/photoTypes", "PhotoTypeController")->except(["index"]);

    Route::resource("/photos", "PhotoController");
    Route::post("/photos/uploadFile", "PhotoController@uploadFile");
    Route::post("/photos/deleteFile", "PhotoController@deleteFile");
    Route::post("/photos/deletePicture/{route}", "PhotoController@deletePicture");

    Route::resource("/logos", "LogoController");
    Route::post("/logos/uploadFile", "LogoController@uploadFile");
    Route::post("/logos/deleteFile", "LogoController@deleteFile");
       
    Route::post("/novedades/uploadFile", "NovedadController@uploadFile");
    Route::post("/novedades/deleteFile", "NovedadController@deleteFile");
    Route::resource("/novedades", "NovedadController")->parameters(['novedades' => 'novedad']);

    Route::resource("/vacantes","VacanteController");
        
    Route::resource("/settings", "SettingController")->except("show");
});

resources/views/novedades/all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ __('novedades.all.title') }}
                        <a class="btn btn-success btn-sm float-right" href="{{route('novedades.create')}}"
                           data-toggle="tooltip" data-placement="right" title="{{__("novedades.save.title")}}">
                            <i class="fa fa-plus"></i> Nueva
                        </a>
                    </div>
                    <div class="card-body">
                        <x-table :columns="$columns" :dataTablesColumns="$dataTablesColumns" :route="$route"
                                 :config="$config" name="novedades"/>
                        <x-modal :title="__('blogs.save.title')" :cancel="true" :save="true" size="modal-lg">
                            <form id="form">
                            <input type="hidden" id="edit">
                            <div class="form-group row">
                                <label for="title" class="col-sm-3 col-form-label">{{__("novedades.labels.title")}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="title"
                                           placeholder="{{__("novedades.labels.title")}}">
                                    <span class="error" id="error_title"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="title" class="col-sm-3 col-form-label">{{__("novedades.labels.category")}}</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="category" id="category">
                                        <option selected>-- Seleccione --</option>

                                    </select>
                                    <span class="error" id="error_category"></span>
                                </div>
                            </div>
                            </form>
                        </x-modal>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        var table;
        let functions = new Functions();
        $(function () {
            $("#alert").hide();
            $('[data-toggle="tooltip"]').tooltip()
        })

        /** start request delete title blogs **/
        function drop(blogId) {
            let response;
            let alert = new Alerts();
            alert.warning(
                "{{__("general.alert-type.warning")}}",
                "{{__("general.delete.message")}}",
                {yes: "{{__("general.buttons.yes")}}", no: "{{__("general.buttons.no")}}"},
                async function () {
                response = await functions.request('{{url("novedades")}}/' + blogId, "DELETE");
                if (response) {
                    swal("{{__("general.delete.title")}}", response, "success");
                    table.ajax.reload();
                }
            });
        }

        /** end request delete blog **/
        /** start request show blog **/
        function show() {
            clearErrors();
            $("#titleModal").html("{{__("novedades.save.title")}}")
            $("#edit").val("");
            $("#form").trigger("reset");
            $("#modal").modal({keyboard: false})
        }
        /** end request show blog **/

        /** start request create title blogs **/
        function create() {
            clearErrors();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{route("novedades.store")}}', "POST", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#text-load").hide();
                $("#primary").removeAttr("disabled");
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Created!", "{{__("novedades.save.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request create blog **/

        /** start request get title blogs **/
        async function get(blogId) {
            let response;
            clearErrors();
            response = await functions.request('{{url("/novedades")}}/'+blogId, "GET");
            if (response) {
                $("#titleModal").html("{{__("novedades.edit.title")}}")
                $("#edit").val(blogId);
                $("#title").val(response.data.title);
                $("#category").val(response.data.category_id).change();
                $("#modal").modal("show");
            }
        }
        /** end request get blog **/

        /** start request edit title blogs **/
        function edit() {
            clearErrors();
            let blogId = $("#edit").val();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{url("/novedades")}}/'+blogId, "PATCH", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Updated!", "{{__("novedades.edit.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request edit blog **/
        function execute() {
            if ($("#edit").val() === "") {
                return create();
            }
            return edit();
        }

        function clearErrors() {
            $("#error_title").html("").hide();
            $("#error_category").html("").hide();
        }
    </script>
@endsection

resources/views/novedades/button_action.blade.php
<div>
    {{--<a type="button" class="btn btn-info btn-sm" href="{{route("novedades.show", $model->getAttribute("id"))}}"
            data-toggle="tooltip" data-placement="right" title="{{__("novedades.all.tooltip-show")}}">
        <i class="fa fa-eye"></i>
    </a>--}}
    <a class="btn btn-warning btn-sm" href="{{route("novedades.edit", $model->getAttribute("id"))}}"
       data-toggle="tooltip" data-placement="right" title="{{__("novedades.all.tooltip-edit")}}">
        <i class="fa fa-pencil"></i>
    </a>
    <button type="button" class="btn btn-danger btn-sm" onclick="drop({{$model->getAttribute("id")}})"
            data-toggle="tooltip" data-placement="right" title="{{__("novedades.all.tooltip-destroy")}}">
        <i class="fa fa-trash"></i>
    </button>
</div>

resources/views/novedades/images.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

    </div>
@endsection

@section("scripts")

@endsection