routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

\Illuminate\Support\Facades\Auth::routes(["register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware("auth")->group(function () {
    Route::resource("/users", "UserController");
    
    Route::get("/photoTypes", "PhotoTypeController@index")->name('photoTypes.index');
    Route::get("/photoTypes/search/{type}", "PhotoTypeController@index");
    Route::get("/photoTypes/create", "PhotoTypeController@create")->name('photoTypes.create');
    Route::post("/photoTypes", "PhotoTypeController@store")->name('photoTypes.store');
    Route::resource("/photoTypes", "PhotoTypeController")->except(["index"]);

    Route::resource("/photos", "PhotoController");
    Route::post("/photos/uploadFile", "PhotoController@uploadFile");
    Route::post("/photos/deleteFile", "PhotoController@deleteFile");
    Route::post("/photos/deletePicture/{route}", "PhotoController@deletePicture");

    Route::resource("/logos", "LogoController");
    Route::post("/logos/uploadFile", "LogoController@uploadFile");
    Route::post("/logos/deleteFile", "LogoController@deleteFile");
       
    Route::post("/novedades/uploadFile", "NovedadController@uploadFile");
    Route::post("/novedades/deleteFile", "NovedadController@deleteFile");
    Route::resource("/novedades", "NovedadController")->parameters(['novedades' => 'novedad']);

    Route::resource("/vacantes","VacanteController");
        
    Route::resource("/settings", "SettingController")->except("show");
});

app/Vacante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vacante extends Model
{
    //
}

app/Http/Controllers/VacanteController.php
<?php

namespace App\Http\Controllers;


use App\Vacante;
use App\Http\Requests\VacanteCreateRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;

class VacanteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function index(Request $request)
    {
          
        $vacantes = Vacante::paginate(10);
                           
        return view("vacantes.all", ['vacantes'=>$vacantes]);
             
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {                        
        return view('vacantes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Vacante $vacante)
    {              
                                          
        $name = $request->input('title');
        $text = $request->input('descripcion');
        
        $vacante->title = $name;
        $vacante->text = $text;

        $vacante->save();
                
            return redirect()->back()->with([
                "message" => "Vacante guardada con éxito"
            ]);
              
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Vacante $vacante)
        {
            return view('vacantes.show', ["vacante"=>$vacante]);
        }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $vacante = Vacante::find($id);

        $vacante->title = $request->input('title');
        $vacante->text = $request->input('descripcion');
        
        if($vacante->isDirty()){
            $vacante->save();
        }
        return redirect()->back()->with([
            "message" => "Vacante editada con éxito"
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vacante $vacante, Request $request )
    {
        $id = str_replace("vacantes/","",$request->path());
        Vacante::where('id', $id)->delete();
        
        return JsonResponse::fromJsonString("Vacante eliminada con éxito");
    }

    
}

resources/views/vacantes/all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Editor de vacantes
                        <a class="btn btn-success btn-sm float-right" href="{{route('vacantes.create')}}"
                           data-toggle="tooltip" data-placement="right" title="Agregar vacante nueva">
                            <i class="fa fa-plus"></i> Nueva
                        </a>
                    </div>
                    <div class="card-body">
                    <table class="table table-striped table-bordered dataTable no-footer">
                        <thead>
                            <tr>
                                <td><strong>ID</strong></td>
                                <td><strong>Nombre</strong></td>
                                <td><strong>Descripción</strong></td>
                                <td><strong>Acciones</strong></td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($vacantes as $vacante)
                            <tr>
                                <td>{{$vacante->id}}</td>
                                <td>{{$vacante->title}}</td>
                                <td>{{$vacante->text}}</td>
                                <td>
                                <a class="btn btn-warning btn-sm" href="http://admin_villaluisa.test/vacantes/{{$vacante->id}}/edit" data-toggle="tooltip" data-placement="right" title="Editar datos de la vacante">
                                    <i class="fa fa-pencil"></i>
                                    </a>
                                  <button type="button" class="btn btn-danger btn-sm" onclick="drop({{$vacante->id}})" data-toggle="tooltip" data-placement="right" title="Eliminar vacante">
                                      <i class="fa fa-trash"></i>
                                  </button>
                                </td>
                                
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $vacantes->links() }}    
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("scripts")
    <script>
        var table;
        
        let functions = new Functions();
        $(function () {
            $("#alert").hide();
            $('[data-toggle="tooltip"]').tooltip()
        })

        /** start request delete title blogs **/
        function drop(blogId) {
            
            let response;
            let alert = new Alerts();
            alert.warning(
                "{{__("general.alert-type.warning")}}",
                "{{__("general.delete.message")}}",
                {yes: "{{__("general.buttons.yes")}}", no: "{{__("general.buttons.no")}}"},
                async function () {
                
                response = await functions.request('{{url("vacantes")}}/' + blogId, "DELETE");
                
                if (response) {
                    swal("{{__("general.delete.title")}}", response, "success");
                    setTimeout(function () { 
                        document.location.reload(true); 
                        }, 2000);
                }
            });
        }

        /** end request delete blog **/
        /** start request show blog **/
        function show() {
            clearErrors();
            $("#titleModal").html("{{__("novedades.save.title")}}")
            $("#edit").val("");
            $("#form").trigger("reset");
            $("#modal").modal({keyboard: false})
            
        }
        /** end request show blog **/

        /** start request create title blogs **/
        function create() {
            clearErrors();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{route("photos.store")}}', "POST", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#text-load").hide();
                $("#primary").removeAttr("disabled");
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Created!", "{{__("novedades.save.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request create blog **/

        /** start request get title blogs **/
        async function get(blogId) {
            let response;
            console.log(blogId);
            clearErrors();
            response = await functions.request('{{url("/photos")}}/'+blogId, "GET");
            
            if (response) {
                $("#titleModal").html("{{__("photos.edit.title")}}")
                $("#edit").val(blogId);
                $("#title").val(response.data.title);
                $("#category").val(response.data.category_id).change();
                $("#modal").modal("show");
            }
        }
        /** end request get blog **/

        /** start request edit title blogs **/
        function edit() {
            clearErrors();
            let blogId = $("#edit").val();
            let data = {
                title: $("#title").val(),
                category:  $("#category").val(),
            };
            functions.request('{{url("/vacantes")}}/'+blogId, "PATCH", data, {}, function () {
                $("#text-create").hide();
                $("#text-load").show();
                $("#load").show();
                $("#primary").attr("disabled", "disabled");
            }).then(() => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                $("#form").trigger("reset");
                table.ajax.reload();
                $("#modal").modal("hide");
                swal("Updated!", "{{__("novedades.edit.message")}}", "success");
            }).catch(err => {
                $("#text-create").show();
                $("#primary").removeAttr("disabled");
                $("#text-load").hide();
                $("#load").hide();
                for (let error in err.responseJSON.errors) {
                    $("#error_"+error).html(err.responseJSON.errors[error]).show();
                }
            });
        }
        /** end request edit blog **/
        function execute() {
            if ($("#edit").val() === "") {
                return create();
            }
            return edit();
        }

        function clearErrors() {
            $("#error_title").html("").hide();
            $("#error_category").html("").hide();
        }
    </script>
@endsection

resources/views/vacantes/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form
            action="{{route("vacantes.store")}}"
            method="POST"
            id="form"
            enctype="multipart/form-data"
        >
          
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <span id="message"></span>
                    <div class="card">
                        <div class="card-header">Subir nueva vacante</div>
                        <div class="card-body">
                            @if ($errors->any() || session()->has("message"))
                                @php
                                    $type = session()->has("message") ? "success" : "danger";
                                    $message = session()->has("message") ? session()->get("message") : "Arreglar los siguientes campos:";
                                @endphp    
                                <x-alert :message="$message" :type="$type" :show="true" duration="100000"/>
                            @endif
                            <div class="form-group">
                                <label for="title">Nombre</label>
                                <input type="text"
                                       class="form-control"
                                       id="title"
                                       name="title"
                                       required
                                       placeholder="Nombre"
                                       value=""
                                />
                            </div>
                            <div class="form-group">
                                <label for="descripcion">Descripción</label>
                                <textarea 
                                type="text"
                                class="form-control"
                                       id="descripcion"
                                       name="descripcion"
                                       required
                                       placeholder="Descripción"
                                       value=""
                                       rows="5"
                                >
                                </textarea>
                            </div>
                                                
                            <div id="kv-avatar-errors-2"></div>
                            <div class="form-group">
                                <button class="btn btn-primary float-right"
                                    id="save">Guardar nueva vacante</button>
                            </div>
                                          
                        </div>
                    </div>
                </div>
                
            </div>
        </form>
    </div>
@endsection
@section("js")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
@endsection
@section('css')
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
@endsection
@section("scripts")
    <script type="application/javascript">
        $(document).ready(function() {
            if (!$("#publish").is(':checked')) {
                $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
            }
            $("#publish").change( function(){
                if( $(this).is(':checked') ) {
                    $("#datetime").removeAttr("readOnly").datepicker("option", "disabled", false);
                }else{
                    $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
                }
            });
            var now = moment();
            let date = $("#datetime").val().length < 0 ? $("#datetime").val() : now.format('DD/MM/YYYY');
            $('#datetime').datepicker({
                changeMonth: true,
                changeYear: true,
            });

            $.datepicker.regional['es'];
        });
        
    </script>
    <script type="application/javascript">

        
        let functions = new Functions();
        
                   
            
        });

        function removeItemFromArr(arr, item) {
            let i = arr.indexOf( item );

            if ( i !== -1 ) {
                arr.splice( i, 1 );
            }
        }

        
    </script>
@endsection

resources/views/vacantes/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form
            action="{{route('vacantes.update',$vacante->id)}}"
            method="POST"
            id="form"
            enctype="multipart/form-data"
        >
        {{ method_field('PUT') }}
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <span id="message"></span>
                    <div class="card">
                        <div class="card-header">Subir nueva vacante</div>
                        <div class="card-body">
                            @if ($errors->any() || session()->has("message"))
                                @php
                                    $type = session()->has("message") ? "success" : "danger";
                                    $message = session()->has("message") ? session()->get("message") : "Arreglar los siguientes campos:";
                                @endphp    
                                <x-alert :message="$message" :type="$type" :show="true" duration="100000"/>
                            @endif
                            <div class="form-group">
                                <label for="title">Nombre</label>
                                <input type="text"
                                       class="form-control"
                                       id="title"
                                       name="title"
                                       required
                                       placeholder="Nombre"
                                       value="{{$vacante->title}}"
                                />
                            </div>
                            <div class="form-group">
                                <label for="descripcion">Descripción</label>
                                <textarea 
                                type="text"
                                class="form-control"
                                       id="descripcion"
                                       name="descripcion"
                                       required
                                       placeholder="Descripción"
                                       value=""
                                       rows="5"
                                >{{$vacante->text}}
                                </textarea>
                            </div>
                                                
                            <div id="kv-avatar-errors-2"></div>
                            <div class="form-group">
                                <button class="btn btn-primary float-right"
                                    id="save">Guardar nueva vacante</button>
                            </div>
                                          
                        </div>
                    </div>
                </div>
                
            </div>
        </form>
    </div>
@endsection
@section("js")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
@endsection
@section('css')
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
@endsection
@section("scripts")
    <script type="application/javascript">
        $(document).ready(function() {
            if (!$("#publish").is(':checked')) {
                $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
            }
            $("#publish").change( function(){
                if( $(this).is(':checked') ) {
                    $("#datetime").removeAttr("readOnly").datepicker("option", "disabled", false);
                }else{
                    $("#datetime").attr("readOnly", "readOnly").datepicker("option", "disabled", true);
                }
            });
            var now = moment();
            let date = $("#datetime").val().length < 0 ? $("#datetime").val() : now.format('DD/MM/YYYY');
            $('#datetime').datepicker({
                changeMonth: true,
                changeYear: true,
            });

            $.datepicker.regional['es'];
        });
        
    </script>
    <script type="application/javascript">

        
        let functions = new Functions();
                   
        });

        function removeItemFromArr(arr, item) {
            let i = arr.indexOf( item );

            if ( i !== -1 ) {
                arr.splice( i, 1 );
            }
        }

        
    </script>
@endsection